from aiogram.types import ReplyKeyboardMarkup, KeyboardButton

bstart = KeyboardButton('/start')
b001 = KeyboardButton('/Кнопка1')
b002 = KeyboardButton('/Кнопка2')
b003 = KeyboardButton('/Кнопка3')
b004 = KeyboardButton('/Кнопка4')
b1 = KeyboardButton('/1экран')
b2 = KeyboardButton('/2проц')
b3 = KeyboardButton('/3ОС')
b4 = KeyboardButton('/4ОПЕР_память')
b5 = KeyboardButton('/5Жесткий_диск')
b6 = KeyboardButton('/6видеокарта')
b7 = KeyboardButton('/7матрица_дисп')
b8 = KeyboardButton('/8сканер_отпеч')
b9 = KeyboardButton('/9подсветка_клав')
b10 = KeyboardButton('/10материал_корп')
b11 = KeyboardButton('/11сенсорный_экран')
b12 = KeyboardButton('/12цвет_корпуса')
b13 = KeyboardButton('/13вес')
b14 = KeyboardButton('/14габариты_ШхДхВ')
b15 = KeyboardButton('/2проц')
b16 = KeyboardButton('/16проц_частота')
b17 = KeyboardButton('/17видеокарта_полн')
b18 = KeyboardButton('/18типа_памяти')
b19 = KeyboardButton('/19частота_памяти')
b20 = KeyboardButton('/20конфигурация_накопит')
b21 = KeyboardButton('/21интерфейсы')
b22 = KeyboardButton('/22беспр_связь')
b23 = KeyboardButton('/2')
b24 = KeyboardButton('/2')
b25 = KeyboardButton('/2')
b26 = KeyboardButton('/2')
b27 = KeyboardButton('/2')
b28 = KeyboardButton('/2')
b29 = KeyboardButton('/2')
b30 = KeyboardButton('/2')
# b2 = KeyboardButton('/2')




kb_client = ReplyKeyboardMarkup(resize_keyboard=True)
kb_notebook1 = ReplyKeyboardMarkup(resize_keyboard=True)
kb_notebook2 = ReplyKeyboardMarkup(resize_keyboard=True)
kb_notebook3 = ReplyKeyboardMarkup(resize_keyboard=True)
kb_notebook4 = ReplyKeyboardMarkup(resize_keyboard=True)
kb_notebook5 = ReplyKeyboardMarkup(resize_keyboard=True)
kb_notebook6 = ReplyKeyboardMarkup(resize_keyboard=True)

kb_client.add(b001).add(b002).add(bstart)
kb_notebook1.row(b1, b2).row(b3, b4, b5).add(bstart)
kb_notebook2.row(b6, b7).row(b8, b9, b10).add(bstart)
kb_notebook3.row(b11, b12).row(b13, b14, b15).add(bstart)
kb_notebook4.row(b16, b17).row(b18, b19, b20).add(bstart)
kb_notebook5.row(b21, b22).row(b23, b24, b25).add(bstart)
kb_notebook6.row(b26, b27).row(b28, b29, b30).add(bstart)
# kb_notebook2.row(b,b).row(b,b,b).add(bstart)
# kb_notebook2.row(b,b).row(b,b,b).add(bstart)

# kb_client.row(b1, b2, b3, b4)