from aiogram.types import ReplyKeyboardMarkup, KeyboardButton

bstart = KeyboardButton('/start')
button0 = KeyboardButton('Загрузить')
b001 = KeyboardButton('/тов1_5')
b002 = KeyboardButton('/тов6_10')
b003 = KeyboardButton('/тов11_15')
b004 = KeyboardButton('/тов16_20')
b005 = KeyboardButton('/тов21_25')
b1 = KeyboardButton('/1_экран')
b2 = KeyboardButton('/2_проц')
b3 = KeyboardButton('/3_Операционная_система')
b4 = KeyboardButton('/4_ОПЕР_память')
b5 = KeyboardButton('/5_Жесткий_диск')
b6 = KeyboardButton('/6_видеокарта')
b7 = KeyboardButton('/7_матрица_дисп')
b8 = KeyboardButton('/8_сканер_отпеч')
b9 = KeyboardButton('/9_подсветка_клав')
b10 = KeyboardButton('/10_материал_корп')
b11 = KeyboardButton('/11_сенсорный_экран')
b12 = KeyboardButton('/12_цвет_корпуса')
b13 = KeyboardButton('/13_вес')
b14 = KeyboardButton('/2_проц')
b15 = KeyboardButton('/15_проц_частота')
b16 = KeyboardButton('/16_видеокарта_полн')
b17 = KeyboardButton('/17_тип_памяти')
b18 = KeyboardButton('/18_частота_памяти')
b19 = KeyboardButton('/19_конф_накопит')
b20 = KeyboardButton('/20_интерфейсы')
b21 = KeyboardButton('/21_беспр_связь')
b22 = KeyboardButton('/22_сдром')
b23 = KeyboardButton('/23_ширина')
b24 = KeyboardButton('/24_глубина')
b25 = KeyboardButton('/25_толщина')




kb_client = ReplyKeyboardMarkup(resize_keyboard=True)
kb_notebook1 = ReplyKeyboardMarkup(resize_keyboard=True)
kb_notebook2 = ReplyKeyboardMarkup(resize_keyboard=True)
kb_notebook3 = ReplyKeyboardMarkup(resize_keyboard=True)
kb_notebook4 = ReplyKeyboardMarkup(resize_keyboard=True)
kb_notebook5 = ReplyKeyboardMarkup(resize_keyboard=True)

kb_client.row(b001, b002, b003).row(b004, b005).add(bstart).add(button0)
kb_notebook1.row(b1, b2).row(b3, b4, b5).add(bstart)
kb_notebook2.row(b6, b7).row(b8, b9, b10).add(bstart)
kb_notebook3.row(b11, b12).row(b13, b14, b15).add(bstart)
kb_notebook4.row(b16, b17).row(b18, b19, b20).add(bstart)
kb_notebook5.row(b21, b22).row(b23, b24, b25).add(bstart)

# kb_client.row(b1, b2, b3, b4)